services:
    keycloak:
        container_name: keycloak
        build:
            context: keycloak
        image: keycloak
        command: ["start-dev",
            "--db=postgres",
            "--db-url=jdbc:postgresql://postgres:5432/keycloak",
            "--db-username=keycloak",
            "--db-password=keycloak",
            "--http-enabled=true",
            "--health-enabled=true",
            "--metrics-enabled=true",
            "--import-realm"     # alles aus dem import-Verzeichnis wird importiert. Die Credentials werden nicht exportiert. Beim Import sind neue Passwörter zu vergeben
            ]
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - 8000:8080
        healthcheck:
            test: timeout 10s bash -c ':> /dev/tcp/localhost/8080'
            interval: 40s
            timeout: 30s
            retries: 3
            start_period: 120s
            start_interval: 5s
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=password
